[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
monitor_filters = direct

upload_speed = 921600

board_build.arduino.memory_type = qio_opi
board_build.psram = enabled

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=3

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    bblanchon/ArduinoJson